### get all persons
GET http://localhost:10001/api/persons

### get info 
GET http://localhost:10001/info

### get person by id
GET http://localhost:10001/api/persons/4

### delete a person by id
DELETE http://localhost:10001/api/persons/69170396d6dc9e54c42ff2ad

### create a new person
POST http://localhost:10001/api/persons
Content-Type: application/json

{
  "name": "King Kong",
  "number": "123456"
}